<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Sounds\Spells\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NAudio" Version="2.2.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Sounds\Spells\Punch_Hit.mp3" />
      <Content Include="Sounds\Spells\Punch_Hit.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Punch_Miss.mp3" />
      <Content Include="Sounds\Spells\Punch_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Astral_Impulse.mp3" />
      <Content Include="Sounds\Spells\Astral_Impulse_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Bottle_Bash_Cast.mp3" />
      <Content Include="Sounds\Spells\Bottle_Bash_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Ice_Arrow_Impact.mp3" />
      <Content Include="Sounds\Spells\Ice_Arrow_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Awakening_Of_The_Ancient_Forest_Impact.mp3" />
      <Content Include="Sounds\Spells\Awakening_Of_The_Ancient_Forest_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Fireball_Impact.mp3" />
      <Content Include="Sounds\Spells\Fireball_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Electric_Discharge_Impact.mp3" />
      <Content Include="Sounds\Spells\Electric_Discharge_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Astral_Impulse_Impact.mp3" />
      <Content Include="Sounds\Spells\Astral_Impulse_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Ice_Arrow_Cast.mp3" />
      <Content Include="Sounds\Spells\Ice_Arrow_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Curse_Of_The_Abyss_Cast.mp3" />
      <Content Include="Sounds\Spells\Curse_Of_The_Abyss_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Thorn_Whip_Cast.mp3" />
      <Content Include="Sounds\Spells\Thorn_Whip_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Corruption_Cast.mp3" />
      <Content Include="Sounds\Spells\Corruption_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Shadow_Strike_Cast.mp3" />
      <Content Include="Sounds\Spells\Shadow_Strike_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Curse_Of_The_Abyss_Impact.mp3" />
      <Content Include="Sounds\Spells\Curse_Of_The_Abyss_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Sharp_Note_Cast.mp3" />
      <Content Include="Sounds\Spells\Dissonance_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Corruption_Impact.mp3" />
      <Content Include="Sounds\Spells\Corruption_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Shadow_Strike_Impact.mp3" />
      <Content Include="Sounds\Spells\Shadow_Strike_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Dissonance_Cast.mp3" />
      <Content Include="Sounds\Spells\Sharp_Note_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Deadly_Performance_Cast.mp3" />
      <Content Include="Sounds\Spells\Deadly_Performance_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Falling_Star_Impact.mp3" />
      <Content Include="Sounds\Spells\Falling_Star_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Falling_Star_Cast.mp3" />
      <Content Include="Sounds\Spells\Falling_Star_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Space_Rift_Cast.mp3" />
      <Content Include="Sounds\Spells\Space_Rift_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Space_Rift_Impact.mp3" />
      <Content Include="Sounds\Spells\Space_Rift_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Fireball_Cast.mp3" />
      <Content Include="Sounds\Spells\Fireball_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Electric_Discharge_Cast.mp3" />
      <Content Include="Sounds\Spells\Electric_Discharge_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Song_Of_Destruction_Cast.mp3" />
      <Content Include="Sounds\Spells\Song_Of_Destruction_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Sharp_Note_Impact.mp3" />
      <Content Include="Sounds\Spells\Sharp_Note_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Dissonance2_Cast.mp3" />
      <Content Include="Sounds\Spells\Dissonance_Cast.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Sounds\Spells\Song_Of_Destruction_Impact.mp3" />
      <Content Include="Sounds\Spells\Song_Of_Destruction_Impact.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
